package com.vet.service;

import com.vet.model.*;
import com.vet.repository.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import java.time.*;
import java.util.*;

@Service
public class AdminService {
 private final UserRepository users; private final PetRepository pets; private final AppointmentRepository appointments; private final PrescriptionRepository prescriptions;
 private final MedicineRepository medicines; private final PharmacyTransactionRepository transactions; private final MedicalReportRepository reports;
 private final AdminActivityLogRepository logs; private final SystemConfigRepository configs; private final PasswordEncoder encoder;
 public AdminService(UserRepository u,PetRepository p,AppointmentRepository a,PrescriptionRepository pr,MedicineRepository m,PharmacyTransactionRepository t,MedicalReportRepository r,AdminActivityLogRepository l,SystemConfigRepository c,PasswordEncoder e){
  users=u;pets=p;appointments=a;prescriptions=pr;medicines=m;transactions=t;reports=r;logs=l;configs=c;encoder=e;
 }
 private User admin(String name){return users.findByUsername(name).orElseThrow(()->new IllegalArgumentException("Admin account not found."));}
 private Map<String,Object> userMap(User u){Map<String,Object>x=new LinkedHashMap<>();x.put("id",u.getId());x.put("username",u.getUsername());x.put("fullName",u.getFullName());x.put("email",u.getEmail());x.put("phone",u.getPhone());x.put("address",u.getAddress());x.put("role",u.getRole());x.put("specialization",u.getSpecialization());x.put("qualification",u.getQualification());x.put("availabilityStatus",u.getAvailabilityStatus());x.put("active",u.getActive());x.put("createdAt",u.getCreatedAt());x.put("lastLogin",u.getLastLogin());return x;}
 public List<Map<String,Object>> userList(String q,String role,String status){List<Map<String,Object>>o=new ArrayList<>();for(User u:users.findAll()){if(q!=null&&!q.trim().isEmpty()){String s=q.toLowerCase();if(!(String.valueOf(u.getId()).contains(s)||u.getUsername().toLowerCase().contains(s)||Objects.toString(u.getFullName(),"").toLowerCase().contains(s)))continue;}if(role!=null&&!role.isEmpty()&&!u.getRole().name().equals(role))continue;if(status!=null&&!status.isEmpty()&&String.valueOf(u.getActive()).equals(status)){} else if(status!=null&&!status.isEmpty())continue;o.add(userMap(u));}return o;}
 public Map<String,Object> saveUser(Map<String,Object>b,Long id,String actor){User u=id==null?new User():users.findById(id).orElseThrow(()->new IllegalArgumentException("User not found."));if(id!=null&&u.getUsername().equals("admin")&&Boolean.FALSE.equals(bool(b.get("active"),true)))throw new IllegalArgumentException("The primary system administrator cannot be deactivated.");String username=Objects.toString(b.get("username"),"").trim();if(username.isEmpty())throw new IllegalArgumentException("Username is required.");u.setUsername(username);u.setFullName(Objects.toString(b.get("fullName"),""));u.setEmail(Objects.toString(b.get("email"),""));u.setPhone(Objects.toString(b.get("phone"),""));u.setAddress(Objects.toString(b.get("address"),""));try{u.setRole(Role.valueOf(Objects.toString(b.get("role"),"PET_OWNER")));}catch(Exception e){throw new IllegalArgumentException("Invalid user role.");}if(id==null){String pw=Objects.toString(b.get("password"),"");if(pw.length()<6)throw new IllegalArgumentException("Password must contain at least 6 characters.");u.setPassword(encoder.encode(pw));u.setCreatedAt(LocalDateTime.now());}else if(b.get("password")!=null&&!Objects.toString(b.get("password"),"").isEmpty())u.setPassword(encoder.encode(b.get("password").toString()));u.setActive(bool(b.get("active"),true));User saved=users.save(u);log(actor,"USER_SAVED","User "+saved.getUsername()+" was created/updated.");return userMap(saved);}
 public Map<String,Object> toggleUser(Long id,boolean active,String actor){User u=users.findById(id).orElseThrow(()->new IllegalArgumentException("User not found."));if(u.getUsername().equals("admin")&&!active)throw new IllegalArgumentException("The primary system administrator cannot be deactivated.");u.setActive(active);users.save(u);log(actor,active?"USER_ACTIVATED":"USER_DEACTIVATED","User "+u.getUsername()+" status changed.");return userMap(u);}
 public List<Map<String,Object>> veterinarians(){List<Map<String,Object>>o=new ArrayList<>();for(User u:users.findByRole(Role.VETERINARIAN)){Map<String,Object>x=userMap(u);x.put("patientCount",pets.findByAssignedVeterinarian(u).size());x.put("prescriptionCount",prescriptions.findByVeterinarian(u).size());x.put("reportCount",reports.findByVeterinarian(u).size());x.put("appointmentCount",appointments.findByVeterinarian(u).size());o.add(x);}return o;}
 public List<Map<String,Object>> owners(){List<Map<String,Object>>o=new ArrayList<>();for(User u:users.findByRole(Role.PET_OWNER)){Map<String,Object>x=userMap(u);x.put("petCount",pets.findByOwner(u).size());o.add(x);}return o;}
 public Map<String,Object> stats(){Map<String,Object>x=new LinkedHashMap<>();x.put("totalUsers",users.count());x.put("totalPetOwners",users.findByRole(Role.PET_OWNER).size());x.put("totalPets",pets.count());x.put("totalVeterinarians",users.findByRole(Role.VETERINARIAN).size());x.put("totalAppointments",appointments.count());x.put("todaysAppointments",appointments.countByAppointmentDate(LocalDate.now()));x.put("completedAppointments",appointments.countByStatus(AppointmentStatus.COMPLETED));x.put("pendingAppointments",appointments.countByStatus(AppointmentStatus.PENDING));x.put("cancelledAppointments",appointments.countByStatus(AppointmentStatus.CANCELLED));x.put("totalPrescriptions",prescriptions.count());x.put("medicinesInStock",medicines.findByActiveTrueOrderByNameAsc().stream().filter(m->m.getQuantity()>0).count());x.put("lowStockMedicines",medicines.findLowStock().size());x.put("medicinesDispensed",transactions.count());x.put("totalPharmacyTransactions",transactions.count());Map<String,Long>species=new LinkedHashMap<>();for(Pet p:pets.findAll())species.put(p.getSpecies()==null?"Unknown":p.getSpecies(),species.getOrDefault(p.getSpecies()==null?"Unknown":p.getSpecies(),0L)+1);x.put("petsBySpecies",species);return x;}
 public Map<String,Object> records(){Map<String,Object>x=new LinkedHashMap<>();x.put("pets",pets.count());x.put("owners",users.findByRole(Role.PET_OWNER).size());x.put("veterinarians",users.findByRole(Role.VETERINARIAN).size());x.put("appointments",appointments.count());x.put("medicalReports",reports.count());x.put("prescriptions",prescriptions.count());x.put("medicines",medicines.count());x.put("pharmacyTransactions",transactions.count());return x;}
 public List<Map<String,Object>> logs(){List<Map<String,Object>>o=new ArrayList<>();for(AdminActivityLog l:logs.findTop100ByOrderByEventTimeDesc()){Map<String,Object>x=new LinkedHashMap<>();x.put("id",l.getId());x.put("action",l.getAction());x.put("description",l.getDescription());x.put("eventTime",l.getEventTime());x.put("user",l.getUser()==null?null:l.getUser().getUsername());o.add(x);}return o;}
 public Map<String,Object> config(){SystemConfig c=configs.findById(1L).orElseGet(()->{SystemConfig n=new SystemConfig();n.setId(1L);n.setHospitalName("Veterinary Hospital");return configs.save(n);});Map<String,Object>x=new LinkedHashMap<>();x.put("hospitalName",c.getHospitalName());x.put("contactInformation",c.getContactInformation());x.put("address",c.getAddress());x.put("operatingHours",c.getOperatingHours());return x;}
 public Map<String,Object> saveConfig(Map<String,Object>b,String actor){SystemConfig c=configs.findById(1L).orElseGet(()->{SystemConfig n=new SystemConfig();n.setId(1L);return n;});c.setHospitalName(Objects.toString(b.get("hospitalName"),""));c.setContactInformation(Objects.toString(b.get("contactInformation"),""));c.setAddress(Objects.toString(b.get("address"),""));c.setOperatingHours(Objects.toString(b.get("operatingHours"),""));configs.save(c);log(actor,"SYSTEM_CONFIG_UPDATED","Hospital system configuration updated.");return config();}
 private boolean bool(Object v,boolean d){return v==null?d:Boolean.parseBoolean(v.toString());}
 private void log(String actor,String action,String description){AdminActivityLog l=new AdminActivityLog();l.setUser(users.findByUsername(actor).orElse(null));l.setAction(action);l.setDescription(description);l.setEventTime(LocalDateTime.now());logs.save(l);}
}
